<?
  include_once ("../../../../lib/inc.php");

  // sanity check

  if (!postcheck ($_REQUEST, ["recid"]))
  {
    $apireturn["status"]["success"] = "false";
    $apireturn["status"]["error"] = "Missing fields";
  }
  else
  {
    // generating auth code

    $_REQUEST["recid"] = mysqli_real_escape_string ($mysql, $_REQUEST["recid"]);
    $auth = md5 ($_REQUEST["recid"]. "-". HASH_SALT);

    if ($_REQUEST["id"])
    {
      // updating apple recommendation id in the concertino db

      $query = "update user set auth='$auth', apple_recid = '{$_REQUEST["recid"]}', lastlogin='". time(). "' where id = '{$_REQUEST["id"]}'";
      mysqli_query ($mysql, $query);

      $apireturn["status"]["success"] = "true";
      $apireturn["user"] = Array ("apple_recid" => $_REQUEST["recid"], "id" => $_REQUEST["id"], "auth" => $auth);
    }
    else
    {
      // registering the user to the concertino db

      $query = "insert into user (auth, apple_recid, lastlogin) values ('$auth', '{$_REQUEST["recid"]}', '". time(). "')
                on duplicate key update id=id, auth='$auth', apple_recid='{$_REQUEST["recid"]}', lastlogin=". time();
      mysqli_query ($mysql, $query);

      $apireturn["status"]["success"] = "true";
      $apireturn["user"] = Array ("apple_recid" => $_REQUEST["recid"], "id" => mysqli_insert_id ($mysql), "auth" => $auth);
    }
  }

  echo apireturn ($apireturn);
