<?
  include_once ("../../../../lib/inc.php");

  // try to find the recording

  $recordings = mysqlfetch ($mysql, "select concat(recording.work_id,'-',recording.apple_albumid,'-',recording.subset) as id, recording.observation as observation, recording.subset, recording.verified, recording.apple_albumid, recording.composer_name as composer_name, recording.work_title as work_title, recording.work_id as work, apple_imgurl as cover, performer, role from recording, recording_performer, user_recording where user_recording.user_id = '{$_REQUEST["id"]}' and user_recording.work_id = recording.work_id and user_recording.apple_albumid = recording.apple_albumid and user_recording.subset = recording.subset and recording_performer.work_id = recording.work_id and recording_performer.subset = recording.subset and recording_performer.apple_albumid = recording.apple_albumid and user_recording.favorite = 1 order by work asc, recording.apple_albumid asc, recording.subset asc");

  if (!$recordings)
  {
    // if there are no recordings, return an error

    $apireturn["status"] = Array ("success"=>"false", "error"=>"No recordings found");
  }
  else
  {
    // recordings exist, list

    // open opus api call

    foreach ($recordings as $rec)
    {
      if (!$rec["composer_name"])
      {
        $worklist[] = $rec["work"];
      }
    }

    if (sizeof ($worklist))
    {
      $obworks = openopusdownparse ("work/list/{$_REQUEST["cid"]}/ids/". implode (",", array_unique ($worklist)). ".json");
    }
    
    foreach ($recordings as $rec)
    {
      if ($lastid != $rec["id"])
      {
        $id = $id + 1;
        $vid = slug ($obworks["works"]["w:". $rec["work"]]["composer"]["name"]. "-". $obworks["works"]["w:". $rec["work"]]["title"]. "-". $id);
        
        $apireturn["recordings"][$vid] = Array
          (
            "apple_albumid" => $rec["apple_albumid"],
            "set" => (Int) $rec["subset"],
            "cover" => $rec["cover"],
            "observation" => $rec["observation"],
            "verified" => $rec["verified"]
          );
      }

      $apireturn["recordings"][$vid]["performers"][] = Array ("name"=>$rec["performer"],"role"=>$rec["role"]);
      $apireturn["recordings"][$vid]["work"] = Array
        (
          "composer"=>Array
            (
              "id"=>($rec["composer_name"] ? "0" : $obworks["works"]["w:". $rec["work"]]["composer"]["id"]),
              "name"=>($rec["composer_name"] ? $rec["composer_name"] : $obworks["works"]["w:". $rec["work"]]["composer"]["name"]),
              "complete_name"=>($rec["composer_name"] ? $rec["composer_name"] : $obworks["works"]["w:". $rec["work"]]["composer"]["complete_name"]),
              "epoch"=>($rec["composer_name"] ? "None" : $obworks["works"]["w:". $rec["work"]]["composer"]["epoch"])
            ),
           "id"=>$rec["work"],
           "title"=>($rec["work_title"] ? $rec["work_title"] : $obworks["works"]["w:". $rec["work"]]["title"]),
           "genre"=>($rec["work_title"] ? "None" : $obworks["works"]["w:". $rec["work"]]["genre"]),
        );

      $lastid = $rec["id"];
    }

    $apirecordings = $apireturn["recordings"];

    foreach ($apirecordings as $apid => $apirec)
    {
      $apirecordings[$apid]["performers"] = orderperformers ($apirec["performers"]);
    }

    ksort ($apirecordings);
    $apireturn["recordings"] = array_values ($apirecordings);
  }

  if (isset ($apireturn["recordings"]))
  {
    $apireturn["status"]["rows"] = sizeof ($apireturn["recordings"]);
    $apireturn["works"] = $obworks["abstract"];

    foreach ($recordings as $rec)
    {
      if ($rec["composer_name"])
      {
        $cn = end (explode (" ", $rec["composer_name"]));
        if (!in_array ($cn, $apireturn["works"]["composers"]["names"]))
        {
          $apireturn["works"]["composers"]["portraits"][] = OPENOPUS_DEFCOMP;
          $apireturn["works"]["composers"]["names"][] = $cn;
          $apireturn["works"]["works"]["rows"] += 1;
        }
      }
    }

    foreach ($apireturn["recordings"] as $rec)
    {
      $apireturn["list"][] = $rec["work"]["id"]. "-". $rec["apple_albumid"]. "-". $rec["set"];
    }

    $apireturn["works"]["composers"]["rows"] = sizeof ($apireturn["works"]["composers"]["names"]);
  }

  echo savecache ("/user/{$_REQUEST["id"]}/recording/fav.json", apireturn ($apireturn));
