<?
  include_once ("../../../../lib/inc.php");

  // try to find the recording

  $recordings = mysqlfetch ($mysql, "select concat(recording.work_id,'-',recording.apple_albumid,'-',recording.subset) as id, recording.observation, recording.subset, recording.verified, recording.apple_albumid, recording.work_id as work, apple_imgurl as cover, performer, role from recording, recording_performer, user_recording where user_recording.user_id = '{$_REQUEST["id"]}' and user_recording.work_id = recording.work_id and user_recording.apple_albumid = recording.apple_albumid and user_recording.subset = recording.subset and recording_performer.work_id = recording.work_id and recording_performer.subset = recording.subset and recording_performer.apple_albumid = recording.apple_albumid order by lastplay desc, work asc, recording.apple_albumid asc, recording.subset asc limit 100");
  
  if (!$recordings)
  {
    // if no recordings exist, return an error

    $apireturn["status"] = Array ("success"=>"false", "error"=>"No recordings found");
  }
  else
  {
    // recordings exist, list

    // open opus api call

    foreach ($recordings as $rec)
    {
      $worklist[] = $rec["work"];
    }

    $obworks = openopusdownparse ("work/list/{$_REQUEST["cid"]}/ids/". implode (",", array_unique ($worklist)). ".json");

    foreach ($recordings as $rec)
    {
      $id = $id + 1;

      if ($lastid != $rec["id"])
      {
        $apireturn["recordings"][$id] = Array
          (
            "apple_albumid" => $rec["apple_albumid"],
            "set" => (Int) $rec["subset"],
            "cover" => $rec["cover"],
            "observation" => $rec["observation"],
            "verified" => $rec["verified"]
          );
      }

      $apireturn["recordings"][$id]["performers"][] = Array ("name"=>$rec["performer"],"role"=>$rec["role"]);
      $apireturn["recordings"][$id]["work"] = Array
        (
          "composer"=>Array
            (
              "id"=>$obworks["works"]["w:". $rec["work"]]["composer"]["id"],
              "name"=>$obworks["works"]["w:". $rec["work"]]["composer"]["name"],
              "complete_name"=>$obworks["works"]["w:". $rec["work"]]["composer"]["complete_name"],
              "epoch"=>$obworks["works"]["w:". $rec["work"]]["composer"]["epoch"]
            ),
           "id"=>$rec["work"],
           "title"=>$obworks["works"]["w:". $rec["work"]]["title"],
           "genre"=>$obworks["works"]["w:". $rec["work"]]["genre"],
        );

      $lastid = $rec["id"];
    }
  }

  if (isset ($apireturn["recordings"]))
  {
    $apireturn["status"]["rows"] = sizeof ($apireturn["recordings"]);
    $apireturn["works"] = $obworks["abstract"];
  }

  echo savecache ("/user/{$_REQUEST["id"]}/recording/recent.json", apireturn ($apireturn));

