<?
  include_once ("../../../../../lib/inc.php");

  // identity check

  if (!simpleauth ($mysql, $_REQUEST["id"], $_REQUEST["auth"]))
  {
    $apireturn["status"]["success"] = "false";
    $apireturn["status"]["error"] = "Authentication failed";
  }
  else if (!postcheck ($_REQUEST, ["wid", "aid", "set"]))
  {
    $apireturn["status"]["success"] = "false";
    $apireturn["status"]["error"] = "Missing fields";
  }
  else
  {
      // everything ok

      $query = "insert into user_recording (user_id, work_id, apple_albumid, subset, favorite) values ('{$_REQUEST["id"]}', '{$_REQUEST["wid"]}', '{$_REQUEST["aid"]}', '{$_REQUEST["set"]}', 0)
                  on duplicate key update favorite = 0";

      mysqli_query ($mysql, $query);

      $apireturn["status"]["success"] = "true";
      $apireturn["favoriterecordings"] = favrecordings ($_REQUEST["id"]);
      $apireturn["user"]["id"] = $_REQUEST["id"];
      $apireturn["recording"] = Array ("work_id"=>$_REQUEST["wid"], "apple_albumid"=>$_REQUEST["aid"], "set"=>$_REQUEST["set"]);
  }

  shell_exec ("rm ". WEBDIR. "/user/{$_REQUEST["id"]}/ -rf");
  echo apireturn ($apireturn);
