<?
  include_once ("../../../../lib/inc.php");

  // sanity check

  if (!postcheck ($_REQUEST, ["token"]))
  {
    $apireturn["status"]["success"] = "false";
    $apireturn["status"]["error"] = "Missing fields";
  }
  else
  {
    //// getting apple recommendation id

    /* disabled by apple
    $recres = appledownparse (APPLEMUSICAPI. "/me/recommendations", APPMUSTOKEN, $_REQUEST["token"]);
    $_REQUEST["recid"] = $recres["data"][0]["id"];
    */

    $_REQUEST["recid"] = uniqid ("conc-", TRUE);

    //// logging in

    // generating auth code

    $_REQUEST["recid"] = mysqli_real_escape_string ($mysql, $_REQUEST["recid"]);
    $auth = md5 ($_REQUEST["recid"]. "-". HASH_SALT);

    // if the request has an id and it fails the authentication, ignores it

    if ($_REQUEST["id"] && !simpleauth ($mysql, $_REQUEST["id"], $_REQUEST["auth"])) $_REQUEST["id"] = 0;

    if ($_REQUEST["id"])
    {
      // if not guest, update apple recommendation id in the concertino db

      if (!stristr ($_REQUEST["recid"], "guest"))
      {
        $query = "update user set apple_recid = '{$_REQUEST["recid"]}', lastlogin='". time(). "', country = '{$_REQUEST["country"]}' where id = '{$_REQUEST["id"]}'";
        mysqli_query ($mysql, $query);
      }
      
      $apireturn["status"]["success"] = "true";
      $udb = mysqlfetch ($mysql, "select heavyuser from user where id='{$_REQUEST["id"]}'");
      $apireturn["user"] = Array ("apple_recid" => $_REQUEST["recid"], "id" => (Integer) $_REQUEST["id"], "heavyuser" => 0);
      //$apireturn["user"] = Array ("apple_recid" => $_REQUEST["recid"], "id" => (Integer) $_REQUEST["id"], "heavyuser" => (Integer) $udb[0]["heavyuser"]);
    }
    else
    {
      // registering the user to the concertino db

      /*$query = "insert into user (auth, apple_recid, lastlogin, country) values ('$auth', '{$_REQUEST["recid"]}', '". time(). "', '{$_REQUEST["country"]}')
                on duplicate key update id=id, apple_recid='{$_REQUEST["recid"]}', country='{$_REQUEST["country"]}', lastlogin=". time();*/
      $query = "insert into user (auth, apple_recid, lastlogin, country) values ('$auth', '{$_REQUEST["recid"]}', '". time(). "', '{$_REQUEST["country"]}')
                on duplicate key update id=id, country='{$_REQUEST["country"]}', lastlogin=". time();
      mysqli_query ($mysql, $query);
      $uid = mysqli_insert_id ($mysql);

      $apireturn["status"]["success"] = "true";
      $udb = mysqlfetch ($mysql, "select auth from user where id='$uid'");
      $apireturn["user"] = Array ("apple_recid" => $_REQUEST["recid"], "id" => $uid, "auth" => $udb[0]["auth"], "heavyuser" => 0); 

      $_REQUEST["id"] = $uid;
    }

    // retrieving user's lists 

    $apireturn["works"] = worklist ($_REQUEST["id"]);
    $apireturn["composerworks"] = workcomposerlist ($_REQUEST["id"]);
    $apireturn["favoriterecordings"] = favrecordings ($_REQUEST["id"]);
    $apireturn["favorite"] = composerlist ("favorite", $_REQUEST["id"]);
    $apireturn["forbidden"] = composerlist ("forbidden", $_REQUEST["id"]);
    $apireturn["playlists"] = playlists ($_REQUEST["id"]);
  }

  echo apireturn ($apireturn);
